# Generated by Django 5.1.6 on 2025-02-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('exchange', models.CharField(default='MEXC', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('price', models.FloatField()),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='monitoring_app.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_time', models.FloatField()),
                ('event_price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring_app.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='TradingPairState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_active', models.BooleanField(default=False)),
                ('peak', models.FloatField(default=0)),
                ('last_ma', models.FloatField(default=0)),
                ('last_updated', models.FloatField(default=0)),
                ('last_pump_start', models.FloatField(default=0)),
                ('last_pump_duration', models.FloatField(default=0)),
                ('pump_start_price', models.FloatField(default=0)),
                ('trading_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='monitoring_app.tradingpair')),
            ],
        ),
    ]
